// Generated by scripts/regen-jurisdictions.py from glasswell.seed.jurisdictions.
// Do not edit: run `make jurisdictions` instead. Registrations only — every count on this
// surface is fetched from /v1/jurisdictions, because a count without the date it was measured
// on is a number nobody can check.

export interface GeneratedJurisdiction {
  /** The registry's own code, e.g. ND. Also the abbreviation the layer panel tags a row with. */
  readonly code: string;
  readonly name: string;
  /** The two leading digits of every API-10 here. An identifier's prefix, not a quantity. */
  readonly prefix: string;
  readonly colour: string;
  readonly wellsTileLayerId: string;
  /** Whether the explorer opens on this jurisdiction. Exactly one registration carries it. */
  readonly explorerDefault: boolean;
  /** Serving rule id per decision, as registered. */
  readonly rules: Readonly<Record<string, string>>;
}

export const JURISDICTION_LIST: readonly GeneratedJurisdiction[] = [
  {
    code: "MT",
    name: "Montana",
    prefix: "25",
    colour: "#7C8B96",
    wellsTileLayerId: "mt_wells",
    explorerDefault: false,
    rules: {
      "absence:operator": "cr_mt_operator_absence_1",
      basin_scope: "cr_mt_basin_scope_1",
      geometry_provenance: "cr_mt_paths_geometry_class_1",
      inventory_jurisdiction: "cr_mt_inventory_jurisdiction_1",
      length_scope: "cr_mt_paths_length_scope_2",
      liquids: "cr_mt_liquids_policy_1",
      neighbors_scope: "cr_mt_neighbors_scope_1",
      status_vocabulary: "cr_mt_gis_status_vocab_1",
    },
  },
  {
    code: "ND",
    name: "North Dakota",
    prefix: "33",
    colour: "#3FA55E",
    wellsTileLayerId: "nd_wells",
    explorerDefault: true,
    rules: {
      basin_scope: "cr_nd_basin_scope_1",
      geometry_provenance: "cr_nd_geometry_provenance_1",
      identity: "cr_nd_api_identity_1",
      inventory_jurisdiction: "cr_nd_inventory_jurisdiction_1",
      length_source: "cr_nd_length_source_1",
      liquids: "cr_nd_liquids_policy_1",
      neighbors_scope: "cr_nd_neighbors_scope_1",
      production_grain: "cr_nd_pool_rollup_1",
      status_vocabulary: "cr_nd_status_vocab_1",
    },
  },
  {
    code: "NM",
    name: "New Mexico",
    prefix: "30",
    colour: "#3FA55E",
    wellsTileLayerId: "nm_wells",
    explorerDefault: false,
    rules: {
      basin_scope: "cr_nm_wellhistory_basin_scope_1",
      geometry_provenance: "cr_nm_wellhistory_geometry_provenance_1",
      identity: "cr_nm_wchistory_api10_1",
      inventory_jurisdiction: "cr_nm_wcproduction_inventory_jurisdiction_1",
      liquids: "cr_nm_wcproduction_liquids_1",
      production_grain: "cr_nm_wcproduction_pool_rollup_1",
      status_vocabulary: "cr_nm_wellhistory_status_vocab_2",
    },
  },
  {
    code: "TX",
    name: "Texas",
    prefix: "42",
    colour: "#7C8B96",
    wellsTileLayerId: "tx_wells",
    explorerDefault: false,
    rules: {
      "absence:operator": "cr_tx_operator_absence_1",
      basin_scope: "cr_tx_basin_scope_1",
      identity: "cr_tx_api10_build_1",
      length_source: "cr_tx_length_source_1",
      status_vocabulary: "cr_tx_status_vocab_1",
    },
  },
];

/** Registered code → registration. Keys are literal so a typo is a type error. */
export const JURISDICTIONS = {
  MT: JURISDICTION_LIST[0]!,
  ND: JURISDICTION_LIST[1]!,
  NM: JURISDICTION_LIST[2]!,
  TX: JURISDICTION_LIST[3]!,
} as const satisfies Readonly<Record<string, GeneratedJurisdiction>>;

/** Registered API prefix → registration. The wire carries the prefix, not the code. */
export const BY_PREFIX: Readonly<Record<string, GeneratedJurisdiction>> =
  Object.fromEntries(JURISDICTION_LIST.map((row) => [row.prefix, row]));

/** The jurisdiction the explorer opens on, registered rather than chosen here. */
export const DEFAULT_JURISDICTION: GeneratedJurisdiction =
  JURISDICTION_LIST.find((row) => row.explorerDefault) ?? JURISDICTION_LIST[0]!;

/** Full name → code, for a label that spells the jurisdiction out. */
export const ABBREVIATION: Readonly<Record<string, string>> =
  Object.fromEntries(JURISDICTION_LIST.map((row) => [row.name, row.code]));

/** The serving rule for one decision in one jurisdiction, or null where none is registered. */
export function jurisdictionRule(code: string, decision: string): string | null {
  return JURISDICTION_LIST.find((row) => row.code === code)?.rules[decision] ?? null;
}

/** Every serving rule id registered for one decision, in code order and deduplicated. */
export function rulesFor(decision: string): readonly string[] {
  const named = JURISDICTION_LIST.map((row) => row.rules[decision]).filter(
    (rule): rule is string => rule !== undefined,
  );
  return [...new Set(named)];
}
