#!/usr/bin/env python3
"""Render the client's registry modules from the jurisdiction registry seed.

Two artifacts, because two readers need different things. `jurisdictions.generated.ts` is the
typed module the bundle imports; `wells-roster.json` is the same wells rows as data, so
`tests/e2e/chrome-fold.mjs` -- plain node ESM with no TypeScript loader -- can read the roster
it asserts over instead of parsing a module as text.

Registrations only — code, name, abbreviation, prefix, colour, tile layer, the presentation
facts each wells row carries, and the rule ids the client names. Counts are deliberately not
generated: a count needs the date it was measured on beside it, and a constant cannot carry
one, so the client fetches those from /v1/jurisdictions at runtime with a loading and a
degraded state (§4 design A). The subtitle is a template with a `{count}` slot for the same
reason: the sentence is a registration and the number in it is not.

Pure Python, no database: the declaration this reads is `glasswell.seed.jurisdictions`, which
`tests/contract/test_jurisdiction_parity.py` holds to the rows the migration wrote.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from glasswell.seed.jurisdictions import JURISDICTION_RULES, JURISDICTIONS, rule_parameters

MAP = Path(__file__).resolve().parents[1] / "web" / "src" / "map"
TARGET = MAP / "jurisdictions.generated.ts"
ROSTER = MAP / "wells-roster.json"

HEADER = """// Generated by scripts/regen-jurisdictions.py from glasswell.seed.jurisdictions.
// Do not edit: run `make jurisdictions` instead. Registrations only — every count on this
// surface is fetched from /v1/jurisdictions, because a count without the date it was measured
// on is a number nobody can check.
"""

TYPES = """
export interface GeneratedJurisdiction {
  /** The registry's own code, e.g. ND. Also the abbreviation the layer panel tags a row with. */
  readonly code: string;
  readonly name: string;
  /** The two leading digits of every API-10 here. An identifier's prefix, not a quantity. */
  readonly prefix: string;
  readonly colour: string;
  readonly wellsTileLayerId: string;
  /** Whether the explorer opens on this jurisdiction. Exactly one registration carries it. */
  readonly explorerDefault: boolean;
  /** The client layer id of this jurisdiction's wells row. North Dakota's is the irregular
   *  "wells": it predates the per-jurisdiction spelling and every saved permalink froze it. */
  readonly wellsLayerId: string;
  /** The style layers that row toggles, in draw order. */
  readonly wellsStyleLayerIds: readonly string[];
  /** A real per-row integer, not a rank: disposal-wells sits at 41, between ND and TX. */
  readonly wellsDrawOrder: number;
  readonly wellsDefaultOn: boolean;
  /** Which measured coverage snapshot the row cites, by key. Null where none is published. */
  readonly wellsSnapshotKey: string | null;
  /** The subtitle with `{count}` where the measured well count goes, filled at render time. */
  readonly wellsSubtitleTemplate: string;
  /** A line the legend renders for this jurisdiction, so no name enters legend.ts. */
  readonly legendNote: string | null;
  /** Serving rule id per decision, as registered. */
  readonly rules: Readonly<Record<string, string>>;
}
"""

FOOTER = """
/** Registered API prefix → registration. The wire carries the prefix, not the code. */
export const BY_PREFIX: Readonly<Record<string, GeneratedJurisdiction>> =
  Object.fromEntries(JURISDICTION_LIST.map((row) => [row.prefix, row]));

/** The jurisdiction the explorer opens on, registered rather than chosen here. */
export const DEFAULT_JURISDICTION: GeneratedJurisdiction =
  JURISDICTION_LIST.find((row) => row.explorerDefault) ?? JURISDICTION_LIST[0]!;

/** Full name → code, for a label that spells the jurisdiction out. */
export const ABBREVIATION: Readonly<Record<string, string>> =
  Object.fromEntries(JURISDICTION_LIST.map((row) => [row.name, row.code]));

/** The serving rule for one decision in one jurisdiction, or null where none is registered. */
export function jurisdictionRule(code: string, decision: string): string | null {
  return JURISDICTION_LIST.find((row) => row.code === code)?.rules[decision] ?? null;
}

/** Every serving rule id registered for one decision, in code order and deduplicated. */
export function rulesFor(decision: string): readonly string[] {
  const named = JURISDICTION_LIST.map((row) => row.rules[decision]).filter(
    (rule): rule is string => rule !== undefined,
  );
  return [...new Set(named)];
}
"""


def _rules(code: str) -> dict[str, str]:
    return {
        str(row["decision"]): str(row["rule_id"])
        for row in (rule_parameters(rule) for rule in JURISDICTION_RULES)
        if row["jurisdiction_code"] == code and row["serving"]
    }


def _optional(value: object) -> str:
    return "null" if value is None else f'"{value}"'


def _wells_layer_id(registration: dict[str, object]) -> str:
    """Refused rather than rendered: `wells_tile_layer_id` is nullable, and an f-string turned
    an explicit None into the literal string "None", which became a provenance source reading
    `marts.None_tile` and a style layer that 404s every tile it asks for."""
    layer = registration.get("wells_tile_layer_id")
    if layer is None:
        code = registration["jurisdiction_code"]
        raise SystemExit(
            f"{code} registers no wells_tile_layer_id; a registration with no tile layer"
            " cannot be rendered as a wells row"
        )
    return str(layer)


def _row(registration: dict[str, object]) -> str:
    code = str(registration["jurisdiction_code"])
    rules = "".join(
        f'      {decision if decision.isidentifier() else f'"{decision}"'}: "{rule_id}",\n'
        for decision, rule_id in sorted(_rules(code).items())
    )
    return (
        "  {\n"
        f'    code: "{code}",\n'
        f'    name: "{registration["name"]}",\n'
        f'    prefix: "{registration["identity_prefix"]}",\n'
        f'    colour: "{registration["map_colour"]}",\n'
        f'    wellsTileLayerId: "{_wells_layer_id(registration)}",\n'
        f"    explorerDefault: {'true' if registration['explorer_default'] else 'false'},\n"
        f'    wellsLayerId: "{registration["wells_layer_id"]}",\n'
        f"    wellsStyleLayerIds: {_string_array(registration['wells_style_layer_ids'])},\n"
        f"    wellsDrawOrder: {registration['wells_draw_order']},\n"
        f"    wellsDefaultOn: {'true' if registration['wells_default_on'] else 'false'},\n"
        f"    wellsSnapshotKey: {_optional(registration['wells_snapshot_key'])},\n"
        f'    wellsSubtitleTemplate: "{registration["wells_subtitle_template"]}",\n'
        f"    legendNote: {_optional(registration['legend_note'])},\n"
        "    rules: {\n"
        f"{rules}"
        "    },\n"
        "  },\n"
    )


def _string_array(values: object) -> str:
    return "[" + ", ".join(f'"{value}"' for value in values) + "]"  # type: ignore[union-attr]


def roster() -> str:
    """The wells rows as data. `tests/e2e/chrome-fold.mjs` is plain node ESM and cannot import
    a TypeScript module, and its refusal on zero rows is what the map-chrome gate rests on."""
    rows = [
        {
            "code": str(row["jurisdiction_code"]),
            "id": str(row["wells_layer_id"]),
            "tileLayerId": _wells_layer_id(row),
            "styleLayers": list(row["wells_style_layer_ids"]),  # type: ignore[arg-type]
            "drawOrder": row["wells_draw_order"],
            "defaultOn": bool(row["wells_default_on"]),
        }
        for row in sorted(JURISDICTIONS, key=lambda row: int(row["wells_draw_order"]))
    ]
    return json.dumps(rows, indent=2) + "\n"


def rendered() -> str:
    rows = "".join(
        _row(row)
        for row in sorted(JURISDICTIONS, key=lambda row: str(row["jurisdiction_code"]))
    )
    codes = sorted(str(row["jurisdiction_code"]) for row in JURISDICTIONS)
    named = "".join(f"  {code}: JURISDICTION_LIST[{index}]!,\n" for index, code in enumerate(codes))
    return (
        HEADER
        + TYPES
        + "\nexport const JURISDICTION_LIST: readonly GeneratedJurisdiction[] = [\n"
        + rows
        + "];\n"
        + "\n/** Registered code → registration. Keys are literal so a typo is a type error. */\n"
        + "export const JURISDICTIONS = {\n"
        + named
        + "} as const satisfies Readonly<Record<string, GeneratedJurisdiction>>;\n"
        + FOOTER
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("target", nargs="?", type=Path, default=TARGET)
    parser.add_argument("--check", action="store_true", help="exit 1 if the file is stale")
    arguments = parser.parse_args(argv)

    roster_target = arguments.target.parent / ROSTER.name
    artifacts = ((arguments.target, rendered()), (roster_target, roster()))
    if arguments.check:
        stale = [
            target
            for target, body in artifacts
            if (target.read_text(encoding="utf-8") if target.is_file() else "") != body
        ]
        if stale:
            named = ", ".join(str(target) for target in stale)
            print(f"{named}: stale; run scripts/regen-jurisdictions.py", file=sys.stderr)
            return 1
        print(f"{arguments.target}: current")
        return 0
    for target, body in artifacts:
        target.write_text(body, encoding="utf-8")
        print(f"{target}: {len(body.splitlines())} lines")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
