#!/usr/bin/env python3
"""Render web/src/map/jurisdictions.generated.ts from the jurisdiction registry seed.

Registrations only — code, name, abbreviation, prefix, colour, tile layer and the rule ids the
client names. Counts are deliberately not generated: a count needs the date it was measured on
beside it, and a constant cannot carry one, so the client fetches those from /v1/jurisdictions
at runtime with a loading and a degraded state (§4 design A).

Pure Python, no database: the declaration this reads is `glasswell.seed.jurisdictions`, which
`tests/contract/test_jurisdiction_parity.py` holds to the rows the migration wrote.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from glasswell.seed.jurisdictions import JURISDICTION_RULES, JURISDICTIONS, rule_parameters

TARGET = (
    Path(__file__).resolve().parents[1] / "web" / "src" / "map" / "jurisdictions.generated.ts"
)

HEADER = """// Generated by scripts/regen-jurisdictions.py from glasswell.seed.jurisdictions.
// Do not edit: run `make jurisdictions` instead. Registrations only — every count on this
// surface is fetched from /v1/jurisdictions, because a count without the date it was measured
// on is a number nobody can check.
"""

TYPES = """
export interface GeneratedJurisdiction {
  /** The registry's own code, e.g. ND. Also the abbreviation the layer panel tags a row with. */
  readonly code: string;
  readonly name: string;
  /** The two leading digits of every API-10 here. An identifier's prefix, not a quantity. */
  readonly prefix: string;
  readonly colour: string;
  readonly wellsTileLayerId: string;
  /** Serving rule id per decision, as registered. */
  readonly rules: Readonly<Record<string, string>>;
}
"""

FOOTER = """
/** Registered API prefix → registration. The wire carries the prefix, not the code. */
export const BY_PREFIX: Readonly<Record<string, GeneratedJurisdiction>> =
  Object.fromEntries(JURISDICTION_LIST.map((row) => [row.prefix, row]));

/** Full name → code, for a label that spells the jurisdiction out. */
export const ABBREVIATION: Readonly<Record<string, string>> =
  Object.fromEntries(JURISDICTION_LIST.map((row) => [row.name, row.code]));

/** The serving rule for one decision in one jurisdiction, or null where none is registered. */
export function jurisdictionRule(code: string, decision: string): string | null {
  return JURISDICTION_LIST.find((row) => row.code === code)?.rules[decision] ?? null;
}

/** Every serving rule id registered for one decision, in code order and deduplicated. */
export function rulesFor(decision: string): readonly string[] {
  const named = JURISDICTION_LIST.map((row) => row.rules[decision]).filter(
    (rule): rule is string => rule !== undefined,
  );
  return [...new Set(named)];
}
"""


def _rules(code: str) -> dict[str, str]:
    return {
        str(row["decision"]): str(row["rule_id"])
        for row in (rule_parameters(rule) for rule in JURISDICTION_RULES)
        if row["jurisdiction_code"] == code and row["serving"]
    }


def _row(registration: dict[str, object]) -> str:
    code = str(registration["jurisdiction_code"])
    rules = "".join(
        f'      {decision if decision.isidentifier() else f'"{decision}"'}: "{rule_id}",\n'
        for decision, rule_id in sorted(_rules(code).items())
    )
    return (
        "  {\n"
        f'    code: "{code}",\n'
        f'    name: "{registration["name"]}",\n'
        f'    prefix: "{registration["identity_prefix"]}",\n'
        f'    colour: "{registration["map_colour"]}",\n'
        f'    wellsTileLayerId: "{registration["wells_tile_layer_id"]}",\n'
        "    rules: {\n"
        f"{rules}"
        "    },\n"
        "  },\n"
    )


def rendered() -> str:
    rows = "".join(
        _row(row)
        for row in sorted(JURISDICTIONS, key=lambda row: str(row["jurisdiction_code"]))
    )
    codes = sorted(str(row["jurisdiction_code"]) for row in JURISDICTIONS)
    named = "".join(f"  {code}: JURISDICTION_LIST[{index}]!,\n" for index, code in enumerate(codes))
    return (
        HEADER
        + TYPES
        + "\nexport const JURISDICTION_LIST: readonly GeneratedJurisdiction[] = [\n"
        + rows
        + "];\n"
        + "\n/** Registered code → registration. Keys are literal so a typo is a type error. */\n"
        + "export const JURISDICTIONS = {\n"
        + named
        + "} as const satisfies Readonly<Record<string, GeneratedJurisdiction>>;\n"
        + FOOTER
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("target", nargs="?", type=Path, default=TARGET)
    parser.add_argument("--check", action="store_true", help="exit 1 if the file is stale")
    arguments = parser.parse_args(argv)

    body = rendered()
    if arguments.check:
        current = arguments.target.read_text(encoding="utf-8") if arguments.target.is_file() else ""
        if current != body:
            print(f"{arguments.target}: stale; run scripts/regen-jurisdictions.py", file=sys.stderr)
            return 1
        print(f"{arguments.target}: current")
        return 0
    arguments.target.write_text(body, encoding="utf-8")
    print(f"{arguments.target}: {len(body.splitlines())} lines")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
